import fs from 'fs';
import path from 'path';

// Load .env.local
const envLocalPath = path.resolve(process.cwd(), '.env.local');
if (fs.existsSync(envLocalPath)) {
  const content = fs.readFileSync(envLocalPath, 'utf-8');
  content.split('\n').forEach((line) => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const idx = trimmed.indexOf('=');
      if (idx !== -1) {
        const k = trimmed.substring(0, idx).trim();
        const v = trimmed.substring(idx + 1).trim();
        if (!process.env[k]) process.env[k] = v;
      }
    }
  });
}

import { getSupabaseAdminClient } from '../src/lib/supabase';

const PROTECTED_ADMIN_EMAIL = 'admin@in.varsaka.com';

interface Classification<T> {
  item: T;
  classification: 'TEST_QA' | 'LEGITIMATE' | 'AMBIGUOUS';
  reason: string;
}

export async function runClassification() {
  const supabase = getSupabaseAdminClient();

  // --------------------------------------------------------------------------
  // 1. CLASSIFY TASKS
  // --------------------------------------------------------------------------
  const { data: taskRecord } = await supabase.from('system_settings').select('*').eq('key', 'tasks_store').maybeSingle();
  const tasks: any[] = (taskRecord && Array.isArray(taskRecord.value)) ? taskRecord.value : [];

  const classifiedTasks: Classification<any>[] = [];
  const seenLegitimateTitles = new Set<string>();

  tasks.forEach((t) => {
    const title = t.title || '';
    const desc = t.description || '';
    const assigned = t.assigned_to;
    const createdBy = t.created_by;

    // A. Explicit test employee / test suite titles
    if (
      title.includes('Disposable Task') ||
      title.includes('Rollback Verification Task') ||
      title.includes('Offboarding Task for Lifecycle Tester') ||
      title.includes('Test Delete Recipient') ||
      title.includes('Aditi Sharma') ||
      desc.includes('verify atomic cascading cleanup') ||
      desc.includes('simulated transaction abort') ||
      desc.includes('Asset return and clearance verification') ||
      title.includes('Invalid Status Test') ||
      title.includes('Invalid Priority Test') ||
      assigned === 'usr-hr-admin-test' ||
      assigned === 'usr-viewer-test' ||
      createdBy === 'super-admin-id' ||
      createdBy === 'usr-super-01' ||
      createdBy === 'admin-super-id'
    ) {
      classifiedTasks.push({
        item: t,
        classification: 'TEST_QA',
        reason: `Explicit QA/Test task signature (title: "${title}", assigned: "${assigned}")`,
      });
      return;
    }

    // B. Check for repeated duplicate operational tasks generated by test suites
    // Canonical operational tasks:
    // - "Self-Assigned Security Audit Review"
    // - "Verify Engineering Relieving Credentials"
    if (title === 'Self-Assigned Security Audit Review' || title === 'Verify Engineering Relieving Credentials') {
      if (!seenLegitimateTitles.has(title)) {
        seenLegitimateTitles.add(title);
        classifiedTasks.push({
          item: t,
          classification: 'LEGITIMATE',
          reason: `Canonical operational administrative task for Super Admin: "${title}"`,
        });
      } else {
        classifiedTasks.push({
          item: t,
          classification: 'TEST_QA',
          reason: `Duplicate test-generated repetition of "${title}" (ID: ${t.id})`,
        });
      }
      return;
    }

    // If any other task exists
    classifiedTasks.push({
      item: t,
      classification: 'AMBIGUOUS',
      reason: `Uncertain task origin (title: "${title}")`,
    });
  });

  const taskStats = {
    total: tasks.length,
    testCandidates: classifiedTasks.filter((c) => c.classification === 'TEST_QA').length,
    legitimate: classifiedTasks.filter((c) => c.classification === 'LEGITIMATE').length,
    ambiguous: classifiedTasks.filter((c) => c.classification === 'AMBIGUOUS').length,
  };

  // --------------------------------------------------------------------------
  // 2. CLASSIFY AUDIT LOGS
  // --------------------------------------------------------------------------
  const { data: auditLogs } = await supabase.from('audit_logs').select('*').order('created_at', { ascending: false });
  const classifiedAudit: Classification<any>[] = [];

  (auditLogs || []).forEach((a) => {
    const user = (a.user_email || a.user_id || '').toLowerCase();
    const action = a.action || '';
    const resId = a.resource_id || '';
    const meta = JSON.stringify(a.metadata || {}).toLowerCase();

    // 1. Confirmed TEST/QA events:
    const isTestUser = (
      user.includes('ok@ok') ||
      user.includes('del.recipient') ||
      user.includes('new.engineer') ||
      user.includes('legacy.test') ||
      user.includes('test.payroll') ||
      user.includes('test.inactive') ||
      user.includes('prot.') ||
      user.includes('rev.emp.') ||
      user.includes('elig.') ||
      user === 'system@varsaka.com' ||
      user === 'system-test@varsaka.com' ||
      user.includes('nonexistent')
    );

    const isTestEmployeeOrDoc = (
      meta.includes('del-147070') ||
      meta.includes('test delete recipient') ||
      meta.includes('aditi sharma') ||
      meta.includes('emp-vl-1025') ||
      meta.includes('emp-vl-1023') ||
      meta.includes('emp-vl-1021') ||
      meta.includes('emp-vl-1001') ||
      meta.includes('emp-prot-') ||
      meta.includes('emp-rev-') ||
      meta.includes('emp-elig-') ||
      meta.includes('check2') ||
      meta.includes('check@gmail.com') ||
      meta.includes('h@h.in') ||
      meta.includes('rehan@in.varsaka.com') ||
      meta.includes('atalkr00@gmail.com') ||
      meta.includes('var-off-2026-001027') ||
      meta.includes('var-off-2026-001028') ||
      meta.includes('var-off-2026-001026') ||
      meta.includes('var-off-2026-001024') ||
      meta.includes('var-off-2026-001022') ||
      meta.includes('var-exp-2026-001029') ||
      meta.includes('var-exp-2026-001028') ||
      meta.includes('var-exp-2026-001027') ||
      meta.includes('var-exp-2026-001026') ||
      meta.includes('var-rel-2026-001006') ||
      meta.includes('var-rel-2026-001005') ||
      meta.includes('var-off-2026-001015') ||
      meta.includes('var-exp-2026-001022') ||
      meta.includes('mixed bulk deletion test execution') ||
      meta.includes('duplicate test draft requiring removal') ||
      meta.includes('tenure dispute; revoking approved document under audit lifecycle') ||
      meta.includes('rehired employee; revoking final separation letter') ||
      meta.includes('scheduled emergency recovery drill') ||
      action === 'SUPER_ADMIN_BREAK_GLASS_RECOVERY' ||
      meta.includes('automated recovery drill lead') ||
      meta.includes('audit verification task') ||
      meta.includes('reactivated for password test') ||
      meta.includes('temporary suspension for audit') ||
      (action === 'USER_CREATED' && (meta.includes('new.engineer') || meta.includes('legacy.test') || meta.includes('test.inactive') || meta.includes('test.payroll')))
    );

    const isTestStaffAction = (
      (action === 'USER_CREATED' && meta.includes('ok@ok')) ||
      (action === 'LOGIN_TEMP_PASSWORD' && user.includes('ok@ok')) ||
      (action === 'USER_PASSWORD_RESET_BY_ADMIN' && meta.includes('new.engineer')) ||
      (action === 'USER_PERMISSION_GRANTED' && meta.includes('hr@in.varsaka.com')) ||
      (action === 'EMPLOYEE_DELETION_REQUESTED' && meta.includes('test delete recipient')) ||
      (action === 'EMPLOYEE_DELETION_APPROVED' && meta.includes('test delete recipient')) ||
      (action === 'TASK_COMPLETED' && resId === 'f9ecd3c5-6ebc-40a9-91a9-c2fc1adf1b81')
    );

    if (isTestUser || isTestEmployeeOrDoc || isTestStaffAction) {
      classifiedAudit.push({
        item: a,
        classification: 'TEST_QA',
        reason: `Confirmed test account, test document, or test runner metadata (Action: ${action}, Res: ${a.resource_type}:${resId})`,
      });
      return;
    }

    // 2. Legitimate events to preserve:
    if (
      (action === 'LOGIN_SUCCESS' || action === 'MFA_SUCCESS' || action === 'MFA_LOGIN_CHALLENGE' || action === 'LOGIN_PASSWORD_VERIFIED') &&
      user === PROTECTED_ADMIN_EMAIL.toLowerCase()
    ) {
      classifiedAudit.push({
        item: a,
        classification: 'LEGITIMATE',
        reason: `Legitimate Super Admin authentication and MFA event: ${action}`,
      });
      return;
    }

    if (action === 'SETTINGS_UPDATED' && resId === 'document_branding' && user === PROTECTED_ADMIN_EMAIL.toLowerCase()) {
      classifiedAudit.push({
        item: a,
        classification: 'LEGITIMATE',
        reason: `Legitimate document branding configuration update by Super Admin`,
      });
      return;
    }

    // Borderline items preserved as AMBIGUOUS
    classifiedAudit.push({
      item: a,
      classification: 'AMBIGUOUS',
      reason: `Preserved: Borderline event associated with admin (Action: ${action}, Res: ${a.resource_type}:${resId})`,
    });
  });

  const auditStats = {
    total: (auditLogs || []).length,
    confirmedTest: classifiedAudit.filter((c) => c.classification === 'TEST_QA').length,
    legitimate: classifiedAudit.filter((c) => c.classification === 'LEGITIMATE').length,
    ambiguous: classifiedAudit.filter((c) => c.classification === 'AMBIGUOUS').length,
  };

  // --------------------------------------------------------------------------
  // 3. CLASSIFY SECURITY LOGS
  // --------------------------------------------------------------------------
  const { data: secLogs } = await supabase.from('security_logs').select('*').order('created_at', { ascending: false });
  const classifiedSec: Classification<any>[] = [];

  (secLogs || []).forEach((s) => {
    const eventType = s.event_type || '';
    const desc = s.description || '';

    // 1. Confirmed TEST/QA Security Logs
    if (
      eventType === 'TEST_SECURITY' ||
      eventType === 'PURGE_TRANSACTION_FAILED' ||
      eventType === 'BREAK_GLASS_INVALID_KEY' ||
      (eventType === 'BREAK_GLASS_EMERGENCY_RECOVERY' && desc.includes('Automated Recovery Drill Lead')) ||
      (eventType === 'AUTH_FAILURE' && (
        desc.includes('new.engineer') ||
        desc.includes('legacy.test') ||
        desc.includes('test.inactive') ||
        desc.includes('test.payroll') ||
        desc.includes('nonexistent.user.99999') ||
        desc.includes('hr@in.varsaka.com') ||
        desc.includes('ok@ok.com')
      ))
    ) {
      classifiedSec.push({
        item: s,
        classification: 'TEST_QA',
        reason: `Confirmed automated test suite event: ${eventType} ("${desc.substring(0, 60)}...")`,
      });
      return;
    }

    // Genuine admin security incident
    if (eventType === 'AUTH_FAILURE' && desc.includes(PROTECTED_ADMIN_EMAIL)) {
      classifiedSec.push({
        item: s,
        classification: 'LEGITIMATE',
        reason: `Legitimate authentication incident for protected administrator`,
      });
      return;
    }

    classifiedSec.push({
      item: s,
      classification: 'AMBIGUOUS',
      reason: `Uncertain security incident origin`,
    });
  });

  const secStats = {
    total: (secLogs || []).length,
    confirmedTest: classifiedSec.filter((c) => c.classification === 'TEST_QA').length,
    legitimate: classifiedSec.filter((c) => c.classification === 'LEGITIMATE').length,
    ambiguous: classifiedSec.filter((c) => c.classification === 'AMBIGUOUS').length,
  };

  return {
    taskStats,
    auditStats,
    secStats,
    classifiedTasks,
    classifiedAudit,
    classifiedSec,
  };
}

if (require.main === module) {
  runClassification().then(({ taskStats, auditStats, secStats, classifiedTasks, classifiedAudit, classifiedSec }) => {
    console.log('================================================================');
    console.log('PHASE A — READ-ONLY DRY RUN REPORT');
    console.log('================================================================\n');

    console.log('TASKS:');
    console.log(`  total: ${taskStats.total}`);
    console.log(`  test candidates: ${taskStats.testCandidates}`);
    console.log(`  legitimate: ${taskStats.legitimate}`);
    console.log(`  ambiguous: ${taskStats.ambiguous}\n`);

    console.log('AUDIT LOGS:');
    console.log(`  total: ${auditStats.total}`);
    console.log(`  confirmed test: ${auditStats.confirmedTest}`);
    console.log(`  legitimate: ${auditStats.legitimate}`);
    console.log(`  ambiguous: ${auditStats.ambiguous}\n`);

    console.log('SECURITY LOGS:');
    console.log(`  total: ${secStats.total}`);
    console.log(`  confirmed test: ${secStats.confirmedTest}`);
    console.log(`  legitimate: ${secStats.legitimate}`);
    console.log(`  ambiguous: ${secStats.ambiguous}\n`);

    console.log('================================================================');
  }).catch(console.error);
}
