'use client';

import React, { useState, useEffect } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import {
  ShieldCheck,
  Copy,
  Check,
  AlertCircle,
  Download,
  CheckCircle2,
} from 'lucide-react';
import { LoadingSpinner, InlineLoader } from '@/components/ui/Loading';

interface MfaEnrollmentCardProps {
  onSuccess?: () => void;
  title?: string;
  subtitle?: string;
}

export default function MfaEnrollmentCard({
  onSuccess,
  title = 'Secure your account',
  subtitle = 'Set up an authenticator app to protect your Varsaka HR account.',
}: MfaEnrollmentCardProps) {
  const [loading, setLoading] = useState(true);
  const [verifying, setVerifying] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  // Enrollment payload
  const [qrUri, setQrUri] = useState<string | null>(null);
  const [manualKey, setManualKey] = useState<string | null>(null);
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const [accountLabel, setAccountLabel] = useState<string>('');
  const [issuer, setIssuer] = useState<string>('Varsaka HR');

  // Verification Input
  const [verificationCode, setVerificationCode] = useState('');
  const [copiedKey, setCopiedKey] = useState(false);
  const [copiedCodes, setCopiedCodes] = useState(false);
  const [hasAcknowledgedRecovery, setHasAcknowledgedRecovery] = useState(false);

  useEffect(() => {
    fetchSetupData();
  }, []);

  const fetchSetupData = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/auth/mfa/setup', {
        method: 'POST',
      });
      const data = await res.json();
      if (!res.ok) {
        if (res.status === 401) {
          throw new Error('Please sign in to your account first before configuring an authenticator.');
        }
        throw new Error(data.error || 'Failed to initialize authenticator setup.');
      }
      setQrUri(data.qrUri);
      setManualKey(data.manualKey);
      setRecoveryCodes(data.recoveryCodes || []);
      setAccountLabel(data.accountLabel || '');
      setIssuer(data.issuer || 'Varsaka HR');
    } catch (err: any) {
      setError(err.message || 'Error generating MFA credentials.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopyKey = () => {
    if (manualKey) {
      navigator.clipboard.writeText(manualKey);
      setCopiedKey(true);
      setTimeout(() => setCopiedKey(false), 2000);
    }
  };

  const handleCopyCodes = () => {
    if (recoveryCodes.length > 0) {
      const text = `Varsaka HR Portal Recovery Codes\nAccount: ${accountLabel}\nIssued: ${new Date().toISOString()}\n\n` +
        recoveryCodes.map((c, i) => `${i + 1}. ${c}`).join('\n') +
        '\n\nTreat these codes like passwords. Each code is single-use.';
      navigator.clipboard.writeText(text);
      setCopiedCodes(true);
      setTimeout(() => setCopiedCodes(false), 2000);
    }
  };

  const handleDownloadCodes = () => {
    if (recoveryCodes.length > 0) {
      const text = `Varsaka HR Portal Emergency Recovery Codes\nAccount: ${accountLabel}\nIssued: ${new Date().toISOString()}\n\n` +
        recoveryCodes.map((c, i) => `${i + 1}. ${c}`).join('\n') +
        '\n\nIMPORTANT: Treat these codes like passwords. Each code can only be used once.';
      const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `varsaka-hr-recovery-codes-${accountLabel.replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  const handleVerifySetup = async (e: React.FormEvent) => {
    e.preventDefault();
    const cleanCode = verificationCode.replace(/\s+/g, '');
    if (!cleanCode || cleanCode.length !== 6) {
      setError('Please enter the 6-digit code generated by your authenticator app.');
      return;
    }

    setVerifying(true);
    setError(null);
    try {
      const res = await fetch('/api/auth/mfa/verify-setup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: cleanCode }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Verification failed.');
      }

      setSuccess(true);
      if (onSuccess) {
        setTimeout(() => {
          onSuccess();
        }, 1500);
      }
    } catch (err: any) {
      setError(err.message || 'Invalid verification code.');
    } finally {
      setVerifying(false);
    }
  };

  if (loading) {
    return (
      <div className="py-12 flex justify-center">
        <InlineLoader text="Generating secure authenticator credentials..." size="md" />
      </div>
    );
  }

  if (success) {
    return (
      <div className="p-8 text-center space-y-4">
        <div className="h-12 w-12 mx-auto rounded-full bg-emerald-50 border border-emerald-200 flex items-center justify-center text-emerald-600">
          <CheckCircle2 className="h-6 w-6" />
        </div>
        <div className="space-y-1">
          <h2 className="text-base font-bold text-slate-900">Authenticator successfully configured.</h2>
          <p className="text-xs text-slate-500">
            Two-factor authentication is now active on your Varsaka HR account.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="text-center space-y-1">
        <div className="h-10 w-10 mx-auto rounded-full bg-blue-50 border border-blue-200 flex items-center justify-center text-blue-600 mb-2">
          <ShieldCheck className="h-5 w-5" />
        </div>
        <h2 className="text-base font-bold text-slate-900">{title}</h2>
        <p className="text-xs text-slate-500 max-w-sm mx-auto">{subtitle}</p>
      </div>

      {error && (
        <div className="p-3 rounded-xl bg-red-50 border border-red-200 text-xs text-red-800 flex items-center justify-between gap-2.5">
          <div className="flex items-center gap-2.5">
            <AlertCircle className="h-4 w-4 shrink-0 text-red-600" />
            <span>{error}</span>
          </div>
          {error.includes('sign in') && (
            <a
              href="/login"
              className="px-2.5 py-1 bg-red-100 hover:bg-red-200 text-red-900 font-bold rounded text-[11px] shrink-0 transition"
            >
              Sign In
            </a>
          )}
        </div>
      )}

      {/* Step 1 & 2: QR Code & Manual Key */}
      <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 sm:p-5 space-y-4">
        <div className="text-xs font-semibold text-slate-700 flex items-center gap-2">
          <span className="flex items-center justify-center h-5 w-5 rounded-full bg-blue-600 text-white text-[10px] font-bold">
            1
          </span>
          <span>Scan QR Code with Authenticator App</span>
        </div>

        <div className="flex flex-col sm:flex-row items-center gap-5 justify-center pt-1">
          {/* QR Code */}
          {qrUri && (
            <div className="bg-white p-3 rounded-xl border border-slate-200 shadow-xs shrink-0 flex items-center justify-center">
              <QRCodeSVG
                value={qrUri}
                size={160}
                level="M"
                marginSize={1}
                aria-label="Authenticator setup QR code"
              />
            </div>
          )}

          {/* Details / Instructions */}
          <div className="space-y-3 text-left max-w-xs">
            <div className="space-y-1">
              <span className="text-[11px] text-slate-500 block uppercase tracking-wider font-semibold">
                Supported Apps
              </span>
              <p className="text-xs text-slate-700 font-medium leading-relaxed">
                Google Authenticator, Microsoft Authenticator, Authy, or any RFC 6238 TOTP app.
              </p>
            </div>

            <div className="space-y-1">
              <span className="text-[11px] text-slate-500 block uppercase tracking-wider font-semibold">
                Account Label
              </span>
              <div className="text-xs font-mono text-slate-800 bg-white px-2.5 py-1 rounded-md border border-slate-200 break-all">
                {accountLabel} ({issuer})
              </div>
            </div>

            {/* Manual Key Fallback */}
            <div className="space-y-1">
              <span className="text-[11px] text-slate-500 block uppercase tracking-wider font-semibold">
                Manual Setup Key
              </span>
              <div className="flex items-center gap-1.5">
                <code className="text-xs font-mono bg-white px-2.5 py-1 rounded-md border border-slate-200 select-all font-bold text-slate-900 break-all">
                  {manualKey}
                </code>
                <button
                  type="button"
                  onClick={handleCopyKey}
                  className="p-1.5 rounded-md hover:bg-slate-200 text-slate-500 hover:text-slate-700 transition cursor-pointer"
                  title="Copy secret key"
                >
                  {copiedKey ? <Check className="h-4 w-4 text-emerald-600" /> : <Copy className="h-4 w-4" />}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Step 2: Emergency Recovery Codes */}
      <div className="bg-amber-50/60 border border-amber-200/80 rounded-xl p-4 sm:p-5 space-y-3">
        <div className="flex items-center justify-between">
          <div className="text-xs font-semibold text-amber-900 flex items-center gap-2">
            <span className="flex items-center justify-center h-5 w-5 rounded-full bg-amber-600 text-white text-[10px] font-bold">
              2
            </span>
            <span>Emergency Recovery Codes</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopyCodes}
              className="inline-flex items-center gap-1 text-[11px] font-semibold text-amber-800 hover:text-amber-950 bg-amber-100 hover:bg-amber-200 px-2 py-1 rounded transition cursor-pointer"
            >
              {copiedCodes ? <Check className="h-3 w-3 text-emerald-600" /> : <Copy className="h-3 w-3" />}
              <span>{copiedCodes ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              type="button"
              onClick={handleDownloadCodes}
              className="inline-flex items-center gap-1 text-[11px] font-semibold text-amber-800 hover:text-amber-950 bg-amber-100 hover:bg-amber-200 px-2 py-1 rounded transition cursor-pointer"
            >
              <Download className="h-3 w-3" />
              <span>Download</span>
            </button>
          </div>
        </div>

        <p className="text-[11px] text-amber-800 font-medium">
          Save these recovery codes in a secure location. They cannot be displayed again.
        </p>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-1">
          {recoveryCodes.map((code, idx) => (
            <div
              key={idx}
              className="bg-white border border-amber-200 rounded-lg p-1.5 text-center font-mono text-xs font-bold text-slate-800 tracking-wider select-all"
            >
              {code}
            </div>
          ))}
        </div>

        <label className="flex items-center gap-2 pt-1 text-[11px] text-amber-900 cursor-pointer select-none">
          <input
            type="checkbox"
            checked={hasAcknowledgedRecovery}
            onChange={(e) => setHasAcknowledgedRecovery(e.target.checked)}
            className="rounded border-amber-300 text-blue-600 focus:ring-blue-500"
          />
          <span>I have securely saved or downloaded my emergency recovery codes</span>
        </label>
      </div>

      {/* Step 3: Verification */}
      <form onSubmit={handleVerifySetup} className="space-y-4">
        <div className="text-xs font-semibold text-slate-700 flex items-center gap-2">
          <span className="flex items-center justify-center h-5 w-5 rounded-full bg-blue-600 text-white text-[10px] font-bold">
            3
          </span>
          <span>Enter 6-Digit Code to Verify</span>
        </div>

        <div>
          <input
            type="text"
            inputMode="numeric"
            maxLength={6}
            value={verificationCode}
            onChange={(e) => setVerificationCode(e.target.value.replace(/[^0-9]/g, ''))}
            placeholder="• • • • • •"
            required
            className="block w-full py-3 px-4 text-center text-xl font-mono tracking-[0.5em] bg-slate-50 border border-slate-300 rounded-xl focus:ring-2 focus:ring-blue-600 focus:bg-white focus:outline-hidden transition text-slate-900 placeholder:text-slate-300 font-bold"
          />
        </div>

        <button
          type="submit"
          disabled={verifying || verificationCode.length !== 6 || !hasAcknowledgedRecovery}
          aria-busy={verifying}
          aria-disabled={verifying || verificationCode.length !== 6 || !hasAcknowledgedRecovery}
          className="w-full flex justify-center items-center gap-2 py-2.5 px-4 border border-transparent rounded-lg text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 focus:outline-hidden focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 shadow-sm transition disabled:opacity-50 cursor-pointer"
        >
          {verifying && <LoadingSpinner size="xs" variant="white" />}
          <span>{verifying ? 'Verifying Code...' : 'Verify & Enable MFA'}</span>
        </button>
      </form>
    </div>
  );
}
